### ISSUE TITLE
Can not upload firmware to SKR mini

### ISSUE THREAD

**Issue by quocanhcgd** [kakou-fr/mmu2s-clone#1]
Help me. Log files:
Configuring upload protocol...
AVAILABLE: blackmagic, dfu, jlink, serial, stlink
CURRENT: upload_protocol = stlink
Uploading .pio\build\mmu-skrmini\firmware.elf
xPack OpenOCD, 64-bit Open On-Chip Debugger 0.10.0+dev (2019-07-17-11:28)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 1

hla_swd
Error: open failed
in procedure 'program'
** OpenOCD init failed **
shutdown command invoked

*** [upload] Error 1

**Comment by kakou-fr** [comment]
you cannot upload it to the board. you must to copy the firmware.bin on the SD card (and remove the BIGTEE... file)

**Comment by quocanhcgd** [comment]
thanks. i will try.
Do you have wiring instructions?

**Comment by quocanhcgd** [comment]
![MMU2S Diagram ](https://user-images.githubusercontent.com/11757368/69204626-0e2d8000-0b7a-11ea-9999-7d1ddf856ac4.jpg)
please review my diagram. Thanks

**Comment by quocanhcgd** [comment]
in your config file i see Color Selector endstop and Filament Switch. Can you tell me about it? is this hardware?

**Comment by kakou-fr** [comment]
thks for the pics, i will add it to the github (or post a pull request ;))
Looks good, only difference is that I use a SKR 1.3 on the printer, so i also connect TX/RX on the TFT board.
I also connect the GND TFT pin to a GND on the main board (in my case on the TFT).
And connected the RESET TFT pin to a pin on the main board (Marlin need to reset the board when it boot, and you can also reset it from the LCD menu)

**Comment by kakou-fr** [comment]
Color Selector endstop : I use an endstop, you can see it on the right https://thingiverse-production-new.s3.amazonaws.com/assets/09/67/85/4a/58/IMG_2221.JPG

Filament Switch : this is the endstop that detect that filament is inserted in the extruder. I use the BNBSX extruder, https://www.thingiverse.com/thing:3626993 , you can see an IR endstop that detect that the filament is inserted in the bondtech gear.

**Comment by quocanhcgd** [comment]
> 
> 
> thks for the pics, i will add it to the github (or post a pull request ;))
> Looks good, only difference is that I use a SKR 1.3 on the printer, so i also connect TX/RX on the TFT board.
> I also connect the GND TFT pin to a GND on the main board (in my case on the TFT).
> And connected the RESET TFT pin to a pin on the main board (Marlin need to reset the board when it boot, and you can also reset it from the LCD menu)

Please explain the detail it. 
In my mind, You use SKR 1.3 and TFT for printer by TFT pin on board and connect to SKR mini to SKR 1.3 by TX/RX. is this right?
If you can, you draw simply for me. i will draw extractly.
Thanks

**Comment by kakou-fr** [comment]
<img width="862" alt="pin_skr_1 3_SKR_MINI" src="https://user-images.githubusercontent.com/29911575/69323557-3e8f2000-0c47-11ea-9cc2-f93ce2a37ade.png">

**Comment by quocanhcgd** [comment]
dear friend.  Do i need edit SKR 1.3 firmware when i connect SKR mini? Please share your firmware of SKR1.3. Thanks

**Comment by quocanhcgd** [comment]
configuration.h 
/**
 * Select the serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT 0

/**
 * Select a secondary serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port -1 is the USB emulated serial port, if available.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2 2
configuration_adv.h 
// #define INTERNAL_SERIAL_PORT 1
  #define MMU2_SERIAL Serial1
is that right?
PLEASE tell me your email or facebook. I need you help?

**Comment by kakou-fr** [comment]
my firmware is here, for SKR1.3<->SKR mini
with some little patch for Marlin to handle correctly the MMU
https://github.com/kakou-fr/Marlin

**Comment by quocanhcgd** [comment]
you use 1.1.9 right?

**Comment by quocanhcgd** [comment]
i want get exactly your firmware because i use skr1.3 and skr mini like you.

**Comment by quocanhcgd** [comment]
SKr 1.3 can't use Marlin 1.1.9

**Comment by kakou-fr** [comment]
32bit boards need Marlin 2.0, and the MMU is also only implemented in the 2.0

**Comment by kakou-fr** [comment]
i need to re push my modification in my fork. look like i forget to push them :) i will do it tomorrow

**Comment by quocanhcgd** [comment]
yes of course
but i have difficult to connect skr v13 with skr mini. I try load filament from menu on LCD 12864  but mortor not moving

**Comment by kakou-fr** [comment]
when you power it, it move (home)?
when you reset from the LCD MENU, it re-home, and you have some traces in the serial console from your printer that say that the MMU is connected ?

**Comment by quocanhcgd** [comment]
when i power MMU buy 12V, it no come home.
when i reset from LCD, the serail console don't talk anything about MMU. I thinks it not connect between SKR and SKR mini.

**Comment by quocanhcgd** [comment]
in configuaration.h i set
#define SERIAL_PORT 0
#define SERIAL_PORT_2 -1
#define BAUDRATE 250000
in configuration_adv.h, i set
 #define INTERNAL_SERIAL_PORT 1
#define MMU2_SERIAL Serial1
#define MMU2_RST_PIN P1_24
Please check, is that right?

**Comment by kakou-fr** [comment]
did you also open a serial connection on the USB of the SKR MINI ? the MMU does nothing if a serial console is not open (for debug and interactive respond)

**Comment by quocanhcgd** [comment]
how can i open serial connection on the USB of the SKR MINI ?

**Comment by quocanhcgd** [comment]
Please tell me other connect to you. Github so slow.

**Comment by quocanhcgd** [comment]
is this right?
#define SERIAL1ENABLED    1

**Comment by kakou-fr** [comment]
connect an usb cable on the SKR-MINI and open a serial console at 115200 (with atom, vscode, arduino ide, ...)

**Comment by quocanhcgd** [comment]
it run :D. how can i chekc load and unload filament? change filament
?

**Comment by kakou-fr** [comment]
power off all
power on the printer
wait marlin boot
power on the mmu
connect the serial console on the mmu
and if all is ok (trace that say that the printer is connected), you can use the mmu from the marlin LCD MENU.

If not, your Marlin firmware is not good. but you can use the serial terminal to send commend to the MMU : 
T0 to load the first filament (T1, ...)
U to unload
C to insert filament in bontech gear
D to launch a debug mode
Z for endstop status
A to test insert/unload of all filament (from 0 to 4)

**Comment by quocanhcgd** [comment]
I run alone MMU is ok but when i connect SKR 1.3 Serial on MMU had notice: ERROR: unrecognized command from the MK3 controller

**Comment by kakou-fr** [comment]
what command did you try to execute ?

**Comment by masgar** [comment]
> I run alone MMU is ok but when i connect SKR 1.3 Serial on MMU had notice: ERROR: unrecognized command from the MK3 controller

I had same problem with latest marlin2. Try to make this changes:

**configuration.h**

```
#define SERIAL_PORT -1
//#define SERIAL_PORT_2 2 //LEAVE COMMENTED
```

**configuration_adv.h**

```
#if ENABLED(PRUSA_MMU2)
  #define MMU2_SERIAL Serial
```

change the file **Marlin/src/feature/prusa_MMU2/mmu2.h** from:

```
#if SERIAL_USB
  #define MMU_RX_SIZE 256
  #define MMU_TX_SIZE 256
#else
  #define MMU_RX_SIZE  16
  #define MMU_TX_SIZE  16
#endif
```

**to**:

```
/*
#if SERIAL_USB
  #define MMU_RX_SIZE 256
  #define MMU_TX_SIZE 256
#else
  #define MMU_RX_SIZE  16
  #define MMU_TX_SIZE  16
#endif
*/

#define MMU_RX_SIZE  1024
#define MMU_TX_SIZE  1024

```
recompile.

Max

**Comment by quocanhcgd** [comment]
OK. Thanks.

**Comment by alequeiroz** [comment]
@kakou-fr is it possible to use a diferent UART from the tft? i was tring to upload a SKR 1.3 (Main) and a ramps 1.4 (MMU), but i have to take the TFT off to use this UART. I tried to use a diferent mmu serial, but i couldnt get any signal, even if i try to connect on the X, Y, Z E0, E1 TMC2208/09 UARTs.

**Comment by gabwhoop** [comment]
if you are use SKR 1.4 Turbo change #define MMU2_RST_PIN P1_24 to #define MMU2_RST_PIN P1_26 and use E0DECT signal pin for reset pin ...... skr 1.4 Turbo does not have PIN P1_24
